name: iOS Unit Testing

on:
  push:
    branches:
      - Tests
  pull_request:
    branches:
      - Tests

jobs:
  test:
    name: Test    
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pod install --repo-update
        shell: bash

      - name: Build and Test
        run: |
          xcodebuild clean test \
          -workspace "PetCare.xcworkspace" \
          -scheme PetCare \
          -destination "${{ matrix.destination }}" \
          -only-testing:PetCareTests \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
        env: 
          destination: ${{ matrix.destination }}
