name: iOS Unit Testing

on:
  push:
    branches:
      - Tests
  pull_request:
    branches:
      - Test

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install

    - name: xcodebuild -version
      run: xcodebuild -version

    - name: Build and test
      run: |
        xcodebuild -workspace 'PetCare.xcworkspace' -scheme 'PetCare' -destination 'platform=iOS Simulator,name=iPhone 13' test