name: iOS Unit Testing

on:
  push:
    branches:
      - Tests
  pull_request:
    branches:
      - Test

jobs:
  build_project:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SwiftFormat
        run: swiftformat . --lint
      - name: SwiftLint
        run: swiftlint lint --strict
      - name: Build and Test
        run: |
          xcodebuild \
           -project [PetCare] \
           -scheme [PetCare] \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
            test || exit 1