
name: iOS Unit Testing

on:
  push:
    branches:
      - Tests
  pull_request:
    branches:
      - Test

jobs:
  build_project:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install-cocoapods-action
        uses: NiftyStack/install-cocoapods-action@1.0.1
      - name: Build and Test
        run: |
           xcodebuild test-without-building -workspace PetCare.xcworkspace -scheme PetCare -destination 'platform=iOS Simulator,name=iPhone 11,OS=17.1' -enableCodeCoverage YES -skip-testing PetCareUITests
